version: '3'

services:
  couchdb:
    container_name: couchdb
    image: apache/couchdb:latest
    ports:
      - "5999:5984"
    environment:
      - COUCHDB_USER=user
      - COUCHDB_PASSWORD=password
    volumes:
      - ./components/infotech-go-test-task/data:/opt/couchdb/data